### ISSUE TITLE
Module 'SwiftPrettyPrint' has no member named 'Debug'

### ISSUE THREAD

**Issue by rzil** [YusukeHosonuma/SwiftPrettyPrint#115]
I always get this error if I try to use `SwiftPrettyPrint.Debug` in my code
`Module 'SwiftPrettyPrint' has no member named 'Debug'`
Help?

**Comment by sahara-ooga** [comment]
SwiftPrittyPrint don't have member named `Debug`, as you mentioned.

As stated in [REAEDME.md](https://github.com/YusukeHosonuma/SwiftPrettyPrint#recommend-settings-) , you can define `typealias Debug` on your own, if you want.
