### ISSUE TITLE
feature: support Combine

### ISSUE THREAD

**Issue by YusukeHosonuma** [YusukeHosonuma/SwiftPrettyPrint#119]
ref: https://developer.apple.com/documentation/combine/publisher/print(_:to:)

My plan is as follows:

```swift
[[1, 2], [3, 4]]
    .publisher
    .prettyPrint("🍎", when: [.request, .value, .completion], format: .multiline, to: nil)
    .sink { _ in }

// =>
// 🍎 request unlimited
// 🍎 receive value:
// [
//     1,
//     2
// ]
// 🍎 receive value:
// [
//     3,
//     4
// ]
// 🍎 receive finished
```

- 1st argument `prefix` and last argument `to` has same functionality of default `print` operator.
- 2nd argument `when` is control when to output.
- 3rd argument `format` is whether to use singleline or multiline as the format.

**Comment by po-miyasaka** [comment]
It seems this issue can be closed.

**Comment by YusukeHosonuma** [comment]
:seyana:
