### ISSUE TITLE
Show URLs as Hyperlinks in colorized logs

### ISSUE THREAD

**Issue by sahara-ooga** [YusukeHosonuma/SwiftPrettyPrint#153]
It would be easier to recognize URLs if the text color were blue and underlined.
In addition, it would be better if the URL could be expanded in the browser when clicked.

related to #143.

**Comment by YusukeHosonuma** [comment]
Let's do it 👍 

> In addition, it would be better if the URL could be expanded in the browser when clicked.

This function is provided from some terminal (such as [iTerm2](https://iterm2.com/)).
![image](https://user-images.githubusercontent.com/2990285/106263263-7f30f300-6267-11eb-928f-b53eaf9ef6eb.png)

So I think, this library is not need to support it :)

**Comment by sahara-ooga** [comment]
> So I think, this library is not need to support it :)

It's good to hear that 😀.
So we concentrate on appearance of URL!

**Comment by sahara-ooga** [comment]
I started to implement the coloring of URL.

**Comment by YusukeHosonuma** [comment]
Resolved in #155
