### ISSUE TITLE
Add public method that returns string

### ISSUE THREAD

**Issue by JediWattson** [YusukeHosonuma/SwiftPrettyPrint#170]
I have a use-case for this library where I would like to take the formatted string and use it to dump some info in the UI. It seems as simple making a method that uses _prettyPrint to return the string, and I made a PR for it.

**Comment by sahara-ooga** [comment]
~~Why is it not sufficient to pass a `String` to the [`output` argument of the `prettyPrint` function](https://github.com/YusukeHosonuma/SwiftPrettyPrint/blob/556e45e4e339e5c07d7461f6396fe9c5c9971f92/Sources/Public/Pretty.swift#L150)?~~ 

~~We're sorry but still don't find a reason why we would implement the public interface.~~

↑ I'm sorry for being so harsh.

I would like to tell you that your demand may be satisfied with the existing API, `prettyPrint` function. The argument `output` argument of the function can be filled with `String` instance.

**Comment by JediWattson** [comment]
Good point, thank you. Perhaps some info in the docs for uninformed 😃

**Comment by sahara-ooga** [comment]
I appreciate your understanding : ).

>  Perhaps some info in the docs for uninformed 😃

I agree. I'll add a note later, thanks!
