### ISSUE TITLE
support: `terminator`

### ISSUE THREAD

**Issue by YusukeHosonuma** [YusukeHosonuma/SwiftPrettyPrint#76]
Like `print` of standard library.
https://developer.apple.com/documentation/swift/1541053-print

**Comment by YusukeHosonuma** [comment]
@sahara-ooga @po-miyasaka 
Please give me your opinions if you has :)

*I think it is unnecessary... should I?*

**Comment by sahara-ooga** [comment]
I think the output string of this library is easiest to read when the terminator is `\n`.
So the `terminator` support has low priority in my opinion.

**Comment by YusukeHosonuma** [comment]
@sahara-ooga Thanks for comment!
I decided that remove this issue from release `1.0.0` :)

**Comment by YusukeHosonuma** [comment]
YAGNI.
