### ISSUE TITLE
feature: common prefix

### ISSUE THREAD

**Issue by YusukeHosonuma** [YusukeHosonuma/SwiftPrettyPrint#82]
## Motivation

Output with conspicuous prefix are useful for search what you want.

For example, use `[DEBUG]` prefix like following:

```text
[DEBUG] "Hello, world"

...other many output...

[DEBUG] "Goodbye..."
```

or emoji:

```text
🍎 "Hello, world"

...other many output...

🍎 "Goodbye..."
```

Therefore introduce common prefix to this library.

## Detail Design

Add `prefix` to `Option`:

```diff
public struct Option {
+   public var prefix: String
    public var indent: Int
}
```

Enable `prefix` to following:

- `print()` function family
- `prettyPrint()` function family
- `p >>>` operator family

Expected behavior is a like following:

```swift
Debug.sharedOption = Debug.option(prefix: "🍎", indent: 2)

let array = ["Hello", "World"]

Debug.print(label: "array", array)
// => 🍎array: ["Hello", "World"]

Debug.p("array") >>> array
// => 🍎array: ["Hello", "World"]

Debug.prettyPrint(label: "array", array)
// =>
// 🍎array:
// [
//   "Hello",
//   "World"
// ]
```

**Comment by YusukeHosonuma** [comment]
@sahara-ooga @po-miyasaka 
Please give me your opinions if you has :)

**Comment by sahara-ooga** [comment]
I like tags ahead of log text. 
It is preferable that you can easily change tag through `Debug.sharedOption` and the specification is optional, in contrast to `Log.d` in Android.
